language: java

sudo: false # faster builds

jdk:
  - oraclejdk8

install:
    true

before_script:
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sh

script:
  - jdk_switcher use oraclejdk8
    - mvn -U -B -V test --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov

notifications:
    email:
      on_failure: change
